Feat: Added support for generation of password rotation report
vmware/powershell-module-for-vmware-cloud-foundation-password-management pull request #115
Opened 2023-09-22 05:04 UTC by sowjuec

### Summary

### Type

- [ ] Bugfix
- [X] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### Test and Documentation

- [X] Tests have been completed.
- [ ] Documentation has been added or updated.

### Issue References

### Additional Information
Though reporting strucuture has a mention of 'Aria' suite components. It it yet to be qualified with VCF5.1

2023-09-22 18:02 UTC, tenthirtyam commented on VMware.CloudFoundation.PasswordManagement.psm1
> +    $Global:reportFolder = $path + '\PasswordRotationManager\'
Could we use `Join-Path` here?

2023-09-22 18:04 UTC, tenthirtyam requested changes
Noticed that an update to the `mkdocs.yml` is needed to include the cmdlet documentation.

2023-09-22 18:05 UTC, tenthirtyam commented on CHANGELOG.md
> +
```suggestion
```

2023-09-22 18:05 UTC, tenthirtyam commented on CHANGELOG.md
> +## UnReleased
```suggestion
## v1.5.0 (Unreleased)
```

2023-09-22 18:06 UTC, tenthirtyam commented on CHANGELOG.md
> +- Updated `Invoke-PasswordPolicyManager`,  `Get-PasswordPolicyDefault`, `Get-PasswordPolicyConfig`, `Request-SddcManagerPasswordComplexity`, `Request-SddcManagerAccountLockout`, `Request-SsoAccountLo
```suggestion
- Updated `Invoke-PasswordPolicyManager`, `Get-PasswordPolicyDefault`, `Get-PasswordPolicyConfig`, `Request-SddcManagerPasswordComplexity`, `Request-SddcManagerAccountLockout`, `Request-SsoAccountLockout`, `Request-VcenterPasswordExpiration`, `Request-VcenterPasswordComplexity`, `Request-VcenterAccountLockout`, `Request-VcenterRootPasswordExpiration`, `Request-NsxtManagerPasswordExpiration`, `Request-NsxtManagerPasswordComplexity`, `Request-NsxtManagerAccountLockout`, `Request-NsxtEdgePasswordExpiration`, `Request-NsxtEdgePasswordComplexity`, `Request-NsxtEdgeAccountLockout`, `Request-EsxiPasswordExpiration`, `Request-EsxiPasswordComplexity`, `Request-EsxiAccountLockout` and `Request-LocalUserPasswordExpiration` cmdlet to simplify the logic for reading version information. [GH-115](https://github.com/vmware/powershell-module-for-vmware-cloud-foundation-password-management/pull/115)
```

2023-09-22 18:07 UTC, tenthirtyam commented on VMware.CloudFoundation.PasswordManagement.psm1
> +                    Write-LogMessage -Type INFO -Message "Collecting Virtual Center Server Single Sign On Rotation for $workflowMessage."
```suggestion
                    Write-LogMessage -Type INFO -Message "Collecting vCenter Server Single Sign-On Rotation for $workflowMessage."
```

2023-09-22 18:07 UTC, tenthirtyam commented on VMware.CloudFoundation.PasswordManagement.psm1
> +                    Write-LogMessage -Type INFO -Message "Collecting WorkSpace One Accesss Password Rotation for $workflowMessage."
```suggestion
                    Write-LogMessage -Type INFO -Message "Collecting WorkSpace ONE Access Password Rotation for $workflowMessage."
```

2023-09-22 18:08 UTC, tenthirtyam commented on VMware.CloudFoundation.PasswordManagement.psm1
> +                    Write-LogMessage -Type INFO -Message "Collecting Virtual Center Server Single Sign On Rotation for $workflowMessage."
```suggestion
                    Write-LogMessage -Type INFO -Message "Collecting vCenter Server Single Sign-On Rotation for $workflowMessage."
```

2023-09-22 18:08 UTC, tenthirtyam commented on VMware.CloudFoundation.PasswordManagement.psm1
> +                    Write-LogMessage -Type INFO -Message "Collecting Virtual Center Server Password Rotation for $workflowMessage."
```suggestion
                    Write-LogMessage -Type INFO -Message "Collecting vCenter Server Password Rotation for $workflowMessage."
```

2023-09-22 18:08 UTC, tenthirtyam commented on VMware.CloudFoundation.PasswordManagement.psm1
> +                    Write-LogMessage -Type INFO -Message "Collecting WorkSpace One Accesss Password Rotation for $workflowMessage."
```suggestion
                    Write-LogMessage -Type INFO -Message "Collecting WorkSpace ONE Access Password Rotation for $workflowMessage."
```

2023-09-22 18:09 UTC, tenthirtyam commented on VMware.CloudFoundation.PasswordManagement.psm1
> +                    Write-LogMessage -Type INFO -Message "Collecting Aria Lifecycle Password Rotation for $workflowMessage."
```suggestion
                    Write-LogMessage -Type INFO -Message "Collecting Aria Suite Lifecycle Password Rotation for $workflowMessage."
```

2023-09-22 18:09 UTC, tenthirtyam commented on VMware.CloudFoundation.PasswordManagement.psm1
> +                    Write-LogMessage -Type INFO -Message "Collecting Aria Lifecycle Password Rotation for $workflowMessage."
```suggestion
                    Write-LogMessage -Type INFO -Message "Collecting Aria Suite Lifecycle Password Rotation for $workflowMessage."
```

2023-09-22 18:10 UTC, tenthirtyam requested changes
Added some minor comments for changes.

2023-09-26 05:19 UTC, tenthirtyam commented
Thanks! I will review very soon.

2023-09-26 13:44 UTC, tenthirtyam commented
@sowjuec I don’t see a new or amended commit with the requested changes. Did you push?

2023-09-27 05:52 UTC, sowjuec commented
> @sowjuec I don’t see a new or amended commit with the requested changes. Did you push?
@tenthirtyam -- could you please check now?

2023-09-27 15:15 UTC, tenthirtyam approved these changes
LGTM! 🚀

2023-09-27 15:19 UTC, merged