feat: Add Pester testcases for testing
vmware/powershell-module-for-vmware-cloud-foundation-password-management pull request #165
Opened 2024-02-27 06:59 UTC by sowjuec

### Summary

 Pester testcases are added to test the password management code and integrate to CD/CI pipeline

### Type

- [ ] Bugfix
- [X] Enhancement or Feature
- [ ] Code Style or Formatting
- [ ] Documentation
- [ ] Refactoring
- [ ] Chore
- [ ] Other
        Please describe:

### Breaking Changes?

- [ ] Yes, there are breaking changes.
- [X] No, there are no breaking changes.

### Test and Documentation

- [X] Tests have been completed.
- [ ] Documentation has been added or updated.

### Issue References

    Closes #162 
    Closes #161 
    Closes #163

### Additional Information

2024-02-27 15:01 UTC, tenthirtyam commented on tests/logs/PPM.Tests.ps1-02-27-2024_07_40_28.log
1. I'd recommend adding a `.gitkeep` file in `./tests/logs` so that it keeps the "empty" directory but default but does not include any of our logs.
2. Update .gitignore to exclude `/tests/logs/`.

```console
# MacOS
## Ignore desktop services files.
**/.DS_Store

# Pester
## Ignore logs directory.
**/tests/logs/**

# MkDocs
## Ignore site directory.
**/.site/**

2024-02-27 15:02 UTC, tenthirtyam commented on tests/InputData.json
> +		"Esxi Server" : [
```suggestion
		"ESXi Hosts" : [
```

Could we update this?

2024-02-27 15:03 UTC, tenthirtyam commented on tests/InputData.json
> +		"Edge Nodes" : [
```suggestion
		"NSX Edge Nodes" : [
```

Could we update this?

2024-02-27 15:03 UTC, tenthirtyam commented on tests/InputData.json
> +		"Manager Node" : [
```suggestion
		"NSX Manager" : [
```

```suggestion
		"NSX Edge Nodes" : [
```

Could we update this?

2024-02-27 15:04 UTC, tenthirtyam commented on tests/InputData.json
> +		"Manager Nodes" : [
```suggestion
		"NSX Manager Nodes" : [
```

Could we update this?

2024-02-27 15:04 UTC, tenthirtyam commented on tests/InputData.json
> +		"Esxi Server" : [
```suggestion
		"ESXI Hosts" : [
```

Could we update this?

2024-02-27 15:05 UTC, tenthirtyam commented on tests/InputData.json
> +		"Edge Nodes" : [
```suggestion
		"NSX Edge Nodes" : [
```

Could we update this?

2024-02-27 15:05 UTC, tenthirtyam commented on tests/InputData.json
> +		"Manager Node" : [
```suggestion
		"NSX Manager" : [
```

Could we update this?

2024-02-27 15:05 UTC, tenthirtyam commented on tests/InputData.json
> +		"Manager Nodes" : [
```suggestion
		"NSX Manager Nodes" : [
```

Could we update this?

2024-02-27 15:06 UTC, tenthirtyam commented on tests/InputData.json
> +		"Cluster"	:	["sfo-m01-cl01"]
```suggestion
		"Clusters"	:	[
			"sfo-m01-cl01"
		]
```

Could we update this since it can take >1.

2024-02-27 15:07 UTC, tenthirtyam commented on tests/InputData.json
> +		"Cluster"	:	["sfo-w01-cl01"]
```suggestion
		"Clusters"	:	[
			"sfo-w01-cl01"
		]
```

Could we update this since it can take >1.

2024-02-27 15:08 UTC, tenthirtyam commented on tests/logs/PPM.Tests.ps1-02-27-2024_07_40_28.log
Delete this log file. 😄

2024-02-27 15:12 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +
```suggestion
```

2024-02-27 15:13 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +
```suggestion
```

2024-02-27 15:13 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +
```suggestion
```

2024-02-27 15:13 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +            }
```suggestion
            }
```

2024-02-27 15:14 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +            #Accepting negative value, So gave bigger value
```suggestion
            # Accepting negative value, so gave bigger value.
```

2024-02-27 15:14 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +        Describe 'NSX edge Password Expiration'  -Tag "NSXEdgePasswordExpiration" {
```suggestion
        Describe 'NSX Edge Password Expiration'  -Tag "NSXEdgePasswordExpiration" {
```

2024-02-27 15:15 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +            #Accepted range of value is <1-9999>
```suggestion
            # Accepted range of value is <1-9999>
```

2024-02-27 15:15 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +                    Write-LogToFile -message "End of NSX edge Password Expiration positive Testcase"
```suggestion
                    Write-LogToFile -message "End of NSX Edge Password Expiration positive Testcase" 
```

2024-02-27 15:35 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
1. `split-path` >> `Split-Path`
2. `join-path` >> `Join-Path`
3. `Write-Host  -NoNewline` >> `Write-Host -NoNewline`
4. `try` >> `Try`
5. `catch` >> `Catch`
6. `finally` >> `Finally`

2024-02-27 15:54 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +        $cluster = $InputData.$domain.'Cluster'[0]
```suggestion
        $cluster = $InputData.$domain.'Clusters'[0]
```

2024-02-27 15:54 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +        $esxiServer = $InputData.$domain.'Esxi Server'[0]
```suggestion
        $esxiServer = $InputData.$domain.'ESXi Hosts'[0]
```

2024-02-27 15:54 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +        $server = $InputData.'SDDCManager'
```suggestion
        $server = $InputData.'SDDC Manager'
```

2024-02-27 15:55 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +        $nsxManagerNode = $InputData.$domain.'Manager Nodes'[0]
```suggestion
        $nsxManagerNode = $InputData.$domain.'NSX Manager Nodes'[0]
```

2024-02-27 15:55 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +        $nsxEdgeNode = $InputData.$domain.'Edge Nodes'[0]
```suggestion
        $nsxEdgeNode = $InputData.$domain.'NSX Edge Nodes'[0]
```

2024-02-27 15:55 UTC, tenthirtyam commented on tests/InputData.json
> +	"Domain"	: 	[
```suggestion
	"Domains"	: 	[
```

2024-02-27 15:55 UTC, tenthirtyam commented on tests/InputData.json
> +	"SDDCManager" : "sfo-vcf01.sfo.rainpole.io",
```suggestion
	"SDDC Manager" : "sfo-vcf01.sfo.rainpole.io",
```

2024-02-27 15:55 UTC, tenthirtyam commented on tests/InputData.json
> +	"SDDCManagerVMName" : "sfo-vcf01",
```suggestion
	"SDDC Manager VM Name" : "sfo-vcf01",
```

2024-02-27 15:56 UTC, tenthirtyam commented on tests/InputData.json
> +	"SsoAdmin"	: "admin@local",
```suggestion
	"SsoAdmin"	: "administrator@local",
```

2024-02-27 15:57 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +        $vmName = $InputData.'SDDCManagerVMName'
```suggestion
        $vmName = $InputData.'SDDC Manager VM Name'
```

2024-02-27 15:57 UTC, tenthirtyam commented on tests/PPM.Tests.ps1
> +        $domain = $InputData.'Domain'[0]
```suggestion
        $domain = $InputData.'Domains'[0]
```

2024-02-27 15:58 UTC, tenthirtyam requested changes
I've performed some cleanup and left the changes to the JSON inputs for your review and comment.

2024-02-29 03:10 UTC, sowjuec commented on tests/InputData.json
> +		"Manager Nodes" : [
yes for sure

2024-02-29 03:11 UTC, sowjuec commented on tests/InputData.json
> +		"Esxi Server" : [
sure

2024-02-29 13:37 UTC, tenthirtyam approved these changes

2024-02-29 13:38 UTC, merged